### ISSUE TITLE
Crash during stack()

### ISSUE THREAD

**Issue by watts4speed** [shelhamer/revolver#3]
Hi I'm trying to run train.py using the Voc dataset.  I'm getting the error below.  For some reason in default_collate(batch)  the batch is not a tuple?  Does this sound familiar?  Any hints on how to fix this?  Thanks, Peter

/home/pmerrill/PycharmProjects/revolver/env/bin/python /home/pmerrill/pycharm/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 46827 --file /home/pmerrill/PycharmProjects/revolver/train.py conditional-lite-sepmetric-class-sbdd-1 --model cofeat-late --dataset voc --datatype late-conditional-class --split trainaug --val_dataset voc --val_split valid --class_group 1 --lr 1e-6 --max_iter 100000 --seed 1337 --gpu 0 --no-eval
Connected to pydev debugger (build 183.5912.18)
pydev debugger: process 18245 is connecting

conditional-lite-sepmetric-class-sbdd-1 already exists. Do you want to obliterate it and continue? [y/N]: y
training conditional-lite-sepmetric-class-sbdd-1
args: {'do_eval': False, 'gpu': 0, 'seed': 1337, 'max_iter': 100000, 'lr': 1e-06, 'shot': 1, 'count': None, 'class_group': '1', 'val_split': 'valid', 'val_dataset': 'voc', 'split': 'trainaug', 'datatype': 'late-conditional-class', 'dataset': 'voc', 'model': 'cofeat-late', 'experiment': 'conditional-lite-sepmetric-class-sbdd-1', 'version': '74f0b0d'}
/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
epoch 0
Traceback (most recent call last):
  File "/home/pmerrill/pycharm/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/pmerrill/pycharm/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/pmerrill/pycharm/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pmerrill/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pmerrill/PycharmProjects/revolver/train.py", line 165, in <module>
    main()
  File "/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmerrill/PycharmProjects/revolver/train.py", line 121, in main
    for i, data in enumerate(loader):
  File "/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/pmerrill/PycharmProjects/revolver/revolver/data/util.py", line 17, in __call__
    inputs[i] = default_collate(input_).unsqueeze(0)
  File "/home/pmerrill/PycharmProjects/revolver/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

Process finished with exit code 1

**Comment by shelhamer** [comment]
Sorry for the trouble! The port to pytorch 1.0 and merge of the interactive and semantic segmentation branches in https://github.com/shelhamer/revolver/commit/000679522ade3d19c8f0b4d3989f0d3521e86b8a does not include all of the updates that it should. I will remedy it soon and report back here.
